#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Sep 18 18:21:40 2023

@author: dai
"""

import mypack.module11 as mym


# import module1

# module1.f1()
# module1.f2()

# import module1 as m1

# m1.f1()
# m1.f2()

# #from module1 import *
# from module1 import f1,f2


# f1()
# f2()

mym.f11()
mym.f21()
